name: Monitoramento com visao computacional com mais cameras
description: ""
ports:
- 8080
- 9393
bricks:
- arduino:telegram_bot:
    variables:
      TELEGRAM_BOT_TOKEN: 8671449367:AAHbDhM1__1WG1cvMFBzb_QrUCBCfF0QpHs
- arduino:web_ui: {}
- video_object_detection:
    model: yolox-object-detection
    devices:
    - remote_camera_0
    - remote_camera_1
icon: 📸
